### ISSUE TITLE
Still issues with ggplot <> data layers errors

### ISSUE THREAD

**Issue by bonnyp** [daroczig/CEU-R-lab#17]
Hi Gergely-

Still seeing issues.  I logged out and logged back into datacamp.  It doesn't like any of the ggplot submissions.  This is the boxplot example from previous screenshots between you and AJ.

![image](https://user-images.githubusercontent.com/32206489/31285189-00bdc6fe-aabb-11e7-814d-b290883b7f81.png)

**Comment by daroczig** [comment]
Can you please refresh the page and start over the homework or at least go back to the previous exercise with the nav bar on the middle top of the screen? After the fix I pushed the other day, the ggplot exercises seems to be OK testing here, not sure what's the problem on your end. Can you please also try the next exercise, eg simply skipping this one?

**Comment by bonnyp** [comment]
I got it working by switching over to Safari on my mac instead of Chrome browser.  I restarted and cleared all the cache data on my Chrome, but it still doesn't work.  Not sure if it is Chrome specifically, but if anyone else hits a problem with ggplot on datacamp, try a different browser.  Safari is ok for me.

Thanks!

**Comment by daroczig** [comment]
Wow, sorry for the tech trouble, but I'm glad you figured this out! I'll let the others also know about this, good idea to try another browser.

**Comment by bonnyp** [comment]
Hi Gergely - just to let you know, this seems to work ok now in Chrome too.  Weird :)
